// Generated by FlutterFire CLI — do not edit manually.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWtij-bar-28B1dD1Zai73itclfW0v670',
    appId: '1:458210612692:android:8c5b5612125c8b0e0bf241',
    messagingSenderId: '458210612692',
    projectId: 'spendsnap-flutter-app',
    storageBucket: 'spendsnap-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ9Q_j0gumDZtZZ838z2fM4xu0aGjyHkg',
    appId: '1:458210612692:ios:3d5747784291c5370bf241',
    messagingSenderId: '458210612692',
    projectId: 'spendsnap-flutter-app',
    storageBucket: 'spendsnap-flutter-app.firebasestorage.app',
    iosBundleId: 'com.spendsnap.spendsnap',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKpWF972S02aTpcK-kH9jOxmLH47UNwlo',
    appId: '1:458210612692:web:b4875fb157955c420bf241',
    messagingSenderId: '458210612692',
    projectId: 'spendsnap-flutter-app',
    authDomain: 'spendsnap-flutter-app.firebaseapp.com',
    storageBucket: 'spendsnap-flutter-app.firebasestorage.app',
  );

}